# Generated by Django 6.0.6 on 2026-06-09 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("yoga", "Yoga & Studio"),
                            ("coffee", "Specialty Coffee"),
                            ("spa", "Spa & Wellness"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(default="Almaty", max_length=64)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("vibe_tags", models.JSONField(default=list)),
                (
                    "editorial_note",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                ("photo_url", models.URLField(blank=True, default="")),
                (
                    "operating_hours",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "Free"), ("featured", "Featured")],
                        default="free",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("avatar_url", models.URLField(blank=True, default="")),
                (
                    "instagram_handle",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "saved_locations",
                    models.ManyToManyField(
                        blank=True, related_name="saved_by", to="core.location"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beacon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("coffee", "Coffee"),
                            ("yoga", "Yoga"),
                            ("walk", "Walk"),
                            ("study", "Study"),
                        ],
                        max_length=15,
                    ),
                ),
                ("message", models.CharField(max_length=100)),
                ("scheduled_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beacons",
                        to="core.location",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beacons",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="BeaconJoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_handle",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beacon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joins",
                        to="core.beacon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beacon_joins",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("beacon", "user")},
            },
        ),
    ]
