# Generated by Django 6.0.6 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="two_gis_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
