# Generated by Django 6.0.6 on 2026-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_location_two_gis_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="beacon",
            name="visibility",
            field=models.CharField(
                choices=[("all", "Everyone"), ("male", "Men"), ("female", "Women")],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vibe_word",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
