"""Almaty wellness venue seed data (~40 hand-picked locations)."""

VENUES = [
    {
        "name": "Mono Coffee",
        "category": "coffee",
        "address": "Kazybek Bi 52, Almaty",
        "latitude": 43.238949,
        "longitude": 76.889709,
        "vibe_tags": ["#Matcha", "#SoftLight", "#Minimal"],
        "editorial_note": "The city's quietest matcha ritual. Floor seating, no laptops after noon.",
        "photo_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
        "operating_hours": "8:00 – 20:00",
        "tier": "featured",
    },
    {
        "name": "Sandyq Coffee",
        "category": "coffee",
        "address": "Kurmangazy 43, Almaty",
        "latitude": 43.2521,
        "longitude": 76.9123,
        "vibe_tags": ["#Specialty", "#Cozy", "#LocalRoast"],
        "editorial_note": "Single-origin pour-overs in a sun-drenched corner of the city.",
        "photo_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
        "operating_hours": "7:30 – 22:00",
        "tier": "free",
    },
    {
        "name": "Aida Coffee",
        "category": "coffee",
        "address": "Dostyk Ave 104, Almaty",
        "latitude": 43.2345,
        "longitude": 76.9567,
        "vibe_tags": ["#Brunch", "#Garden", "#Aesthetic"],
        "editorial_note": "Brunch plates and flat whites under fig trees.",
        "photo_url": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
        "operating_hours": "9:00 – 23:00",
        "tier": "featured",
    },
    {
        "name": "Traveler's Coffee",
        "category": "coffee",
        "address": "Furmanov 164, Almaty",
        "latitude": 43.2412,
        "longitude": 76.9234,
        "vibe_tags": ["#RemoteWork", "#Quiet", "#WiFi"],
        "editorial_note": "A calm workspace with excellent espresso and natural light.",
        "photo_url": "https://images.unsplash.com/photo-1453614512568-c3b9c14866b0?w=800",
        "operating_hours": "8:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "Café Central",
        "category": "coffee",
        "address": "Gogol 40, Almaty",
        "latitude": 43.2567,
        "longitude": 76.9456,
        "vibe_tags": ["#Classic", "#Terrace", "#PeopleWatch"],
        "editorial_note": "Old Almaty charm with a modern coffee program.",
        "photo_url": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
        "operating_hours": "7:00 – 23:00",
        "tier": "free",
    },
    {
        "name": "Raf Coffee",
        "category": "coffee",
        "address": "Zheltoksan 67, Almaty",
        "latitude": 43.2489,
        "longitude": 76.9345,
        "vibe_tags": ["#Raf", "#Indie", "#Vinyl"],
        "editorial_note": "Where Almaty's creative class gathers for afternoon raf.",
        "photo_url": "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800",
        "operating_hours": "9:00 – 22:00",
        "tier": "free",
    },
    {
        "name": "Yoga Space Almaty",
        "category": "yoga",
        "address": "Satpaev 90, Almaty",
        "latitude": 43.2312,
        "longitude": 76.9123,
        "vibe_tags": ["#Vinyasa", "#MorningFlow", "#Community"],
        "editorial_note": "Sunrise flows with views of the mountains. Book ahead on weekends.",
        "photo_url": "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800",
        "operating_hours": "6:00 – 21:00",
        "tier": "featured",
    },
    {
        "name": "Pilates Lab",
        "category": "yoga",
        "address": "Abay 52, Almaty",
        "latitude": 43.2445,
        "longitude": 76.9012,
        "vibe_tags": ["#Reformer", "#Core", "#SmallGroups"],
        "editorial_note": "Reformer pilates in a bright, plant-filled studio.",
        "photo_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800",
        "operating_hours": "7:00 – 20:00",
        "tier": "free",
    },
    {
        "name": "Zen Studio",
        "category": "yoga",
        "address": "Baitursynov 55, Almaty",
        "latitude": 43.2298,
        "longitude": 76.8876,
        "vibe_tags": ["#Yin", "#Meditation", "#Silence"],
        "editorial_note": "Evening yin and sound baths. Phones off at the door.",
        "photo_url": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
        "operating_hours": "8:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "Flow House",
        "category": "yoga",
        "address": "Timiryazev 42, Almaty",
        "latitude": 43.2612,
        "longitude": 76.9234,
        "vibe_tags": ["#HotYoga", "#Sweat", "#Energy"],
        "editorial_note": "Heated vinyasa for those who like it intense.",
        "photo_url": "https://images.unsplash.com/photo-1599901860904-17e06e708fff?w=800",
        "operating_hours": "6:30 – 21:30",
        "tier": "free",
    },
    {
        "name": "Mountain Yoga",
        "category": "yoga",
        "address": "Dostyk 280, Almaty",
        "latitude": 43.2156,
        "longitude": 76.9678,
        "vibe_tags": ["#Outdoor", "#Views", "#Weekend"],
        "editorial_note": "Rooftop sessions when the weather allows. Magic at golden hour.",
        "photo_url": "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=800",
        "operating_hours": "Weekends 7:00 – 12:00",
        "tier": "featured",
    },
    {
        "name": "Arasan Wellness",
        "category": "spa",
        "address": "Kunaev 42, Almaty",
        "latitude": 43.2534,
        "longitude": 76.9567,
        "vibe_tags": ["#Sauna", "#Banya", "#Historic"],
        "editorial_note": "Soviet-era wellness reimagined. The birch branch ritual is essential.",
        "photo_url": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800",
        "operating_hours": "10:00 – 22:00",
        "tier": "featured",
    },
    {
        "name": "Santai Spa",
        "category": "spa",
        "address": "Rozybakiev 247, Almaty",
        "latitude": 43.2089,
        "longitude": 76.8934,
        "vibe_tags": ["#Massage", "#Luxury", "#Couples"],
        "editorial_note": "Balinese-inspired treatments in the foothills.",
        "photo_url": "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
        "operating_hours": "10:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "Green Bathhouse",
        "category": "spa",
        "address": "Shevchenko 145, Almaty",
        "latitude": 43.2678,
        "longitude": 76.9123,
        "vibe_tags": ["#Hammam", "#Relax", "#Local"],
        "editorial_note": "A hidden hammam loved by locals. Bring your own flip-flops.",
        "photo_url": "https://images.unsplash.com/photo-1600334089648-4e4a5ae646cc?w=800",
        "operating_hours": "9:00 – 20:00",
        "tier": "free",
    },
    {
        "name": "Aura Float",
        "category": "spa",
        "address": "Al-Farabi 77, Almaty",
        "latitude": 43.2234,
        "longitude": 76.9345,
        "vibe_tags": ["#Float", "#Sensory", "#Reset"],
        "editorial_note": "Sensory deprivation tanks for deep reset. Book 90 minutes minimum.",
        "photo_url": "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800",
        "operating_hours": "10:00 – 22:00",
        "tier": "free",
    },
    {
        "name": "Botanica Juice Bar",
        "category": "other",
        "address": "Panfilov 73, Almaty",
        "latitude": 43.2567,
        "longitude": 76.9456,
        "vibe_tags": ["#ColdPress", "#Vegan", "#Green"],
        "editorial_note": "Cold-pressed everything. The turmeric latte is a city legend.",
        "photo_url": "https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800",
        "operating_hours": "8:00 – 20:00",
        "tier": "free",
    },
    {
        "name": "Green Market Café",
        "category": "other",
        "address": "Zhibek Zholy 53, Almaty",
        "latitude": 43.2598,
        "longitude": 76.9512,
        "vibe_tags": ["#Organic", "#Market", "#Seasonal"],
        "editorial_note": "Farm-to-table bowls next to the green bazaar.",
        "photo_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
        "operating_hours": "8:00 – 18:00",
        "tier": "free",
    },
    {
        "name": "Book & Brew",
        "category": "coffee",
        "address": "Karasai Batyr 62, Almaty",
        "latitude": 43.2456,
        "longitude": 76.8789,
        "vibe_tags": ["#Books", "#Study", "#Quiet"],
        "editorial_note": "Curated shelves and pour-over. Perfect for solo afternoons.",
        "photo_url": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800",
        "operating_hours": "10:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "Sunrise Run Club",
        "category": "other",
        "address": "First President's Park, Almaty",
        "latitude": 43.2012,
        "longitude": 76.9789,
        "vibe_tags": ["#Running", "#Community", "#Morning"],
        "editorial_note": "Meet at the fountain. 6km loop through the park every Saturday.",
        "photo_url": "https://images.unsplash.com/photo-1476480862128-209bfaa8edc8?w=800",
        "operating_hours": "Sat 7:00 AM",
        "tier": "free",
    },
    {
        "name": "Kok-Tobe Trail",
        "category": "other",
        "address": "Kok-Tobe, Almaty",
        "latitude": 43.2289,
        "longitude": 76.9789,
        "vibe_tags": ["#Hike", "#Views", "#Nature"],
        "editorial_note": "Urban hike with panoramic city views. Best at sunset.",
        "photo_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
        "operating_hours": "Dawn – Dusk",
        "tier": "featured",
    },
    {
        "name": "Nursultan Coffee",
        "category": "coffee",
        "address": "Tole Bi 59, Almaty",
        "latitude": 43.2512,
        "longitude": 76.9234,
        "vibe_tags": ["#Espresso", "#Fast", "#Central"],
        "editorial_note": "Quick specialty shots for the downtown crowd.",
        "photo_url": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800",
        "operating_hours": "7:00 – 20:00",
        "tier": "free",
    },
    {
        "name": "Lotus Meditation",
        "category": "yoga",
        "address": "Masanchi 78, Almaty",
        "latitude": 43.2634,
        "longitude": 76.9345,
        "vibe_tags": ["#Meditation", "#Breathwork", "#Calm"],
        "editorial_note": "Guided breathwork sessions twice daily.",
        "photo_url": "https://images.unsplash.com/photo-1528319725582-ddc096101511?w=800",
        "operating_hours": "7:00 – 19:00",
        "tier": "free",
    },
    {
        "name": "Steam & Stone",
        "category": "spa",
        "address": "Raiymbek 348, Almaty",
        "latitude": 43.2123,
        "longitude": 76.8567,
        "vibe_tags": ["#Sauna", "#ColdPlunge", "#Recovery"],
        "editorial_note": "Contrast therapy for athletes and wellness seekers.",
        "photo_url": "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800",
        "operating_hours": "8:00 – 22:00",
        "tier": "free",
    },
    {
        "name": "Dala Coffee Roasters",
        "category": "coffee",
        "address": "Bogenbay Batyr 142, Almaty",
        "latitude": 43.2478,
        "longitude": 76.9123,
        "vibe_tags": ["#Roastery", "#SingleOrigin", "#Tasting"],
        "editorial_note": "Watch beans roast while you sip cupping flights.",
        "photo_url": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800",
        "operating_hours": "9:00 – 19:00",
        "tier": "featured",
    },
    {
        "name": "Stretch Society",
        "category": "yoga",
        "address": "Nauryzbay Batyr 28, Almaty",
        "latitude": 43.2345,
        "longitude": 76.9012,
        "vibe_tags": ["#Mobility", "#Stretch", "#Recovery"],
        "editorial_note": "Mobility classes for desk workers and runners alike.",
        "photo_url": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800",
        "operating_hours": "8:00 – 20:00",
        "tier": "free",
    },
    {
        "name": "Mediterraneo",
        "category": "other",
        "address": "Kurmangazy 89, Almaty",
        "latitude": 43.2589,
        "longitude": 76.9234,
        "vibe_tags": ["#Mediterranean", "#Lunch", "#Terrace"],
        "editorial_note": "Light Mediterranean plates with a wellness-forward menu.",
        "photo_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "operating_hours": "11:00 – 23:00",
        "tier": "free",
    },
    {
        "name": "Cloud Nine Café",
        "category": "coffee",
        "address": "Shagabutdinov 12, Almaty",
        "latitude": 43.2267,
        "longitude": 76.9456,
        "vibe_tags": ["#CloudCoffee", "#Instagram", "#Dessert"],
        "editorial_note": "Fluffy cloud lattes and pastel interiors.",
        "photo_url": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
        "operating_hours": "10:00 – 22:00",
        "tier": "free",
    },
    {
        "name": "Breath & Body",
        "category": "yoga",
        "address": "Furmanov 128, Almaty",
        "latitude": 43.2423,
        "longitude": 76.9178,
        "vibe_tags": ["#Pilates", "#Barre", "#Tone"],
        "editorial_note": "Barre and mat pilates fusion classes.",
        "photo_url": "https://images.unsplash.com/photo-1574680096145-d05b474e7655?w=800",
        "operating_hours": "7:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "Thermal Springs",
        "category": "spa",
        "address": "Kapchagay Road, Almaty Region",
        "latitude": 43.1890,
        "longitude": 76.8234,
        "vibe_tags": ["#HotSprings", "#DayTrip", "#Nature"],
        "editorial_note": "Natural hot springs — worth the short drive out of the city.",
        "photo_url": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800",
        "operating_hours": "9:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "The Matcha Bar",
        "category": "coffee",
        "address": "Abylaikhan 52, Almaty",
        "latitude": 43.2490,
        "longitude": 76.9340,
        "vibe_tags": ["#Matcha", "#Ceremony", "#Japanese"],
        "editorial_note": "Ceremonial grade matcha prepared with intention.",
        "photo_url": "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=800",
        "operating_hours": "9:00 – 19:00",
        "tier": "featured",
    },
    {
        "name": "Urban Garden Studio",
        "category": "yoga",
        "address": "Kazybek Bi 135, Almaty",
        "latitude": 43.2367,
        "longitude": 76.9012,
        "vibe_tags": ["#Garden", "#Outdoor", "#Flow"],
        "editorial_note": "Open-air yoga in a hidden courtyard garden.",
        "photo_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
        "operating_hours": "May – Sep, 7:00 – 10:00",
        "tier": "free",
    },
    {
        "name": "Silence Room",
        "category": "spa",
        "address": "Dostyk 89, Almaty",
        "latitude": 43.2412,
        "longitude": 76.9567,
        "vibe_tags": ["#Silence", "#Rest", "#Nap"],
        "editorial_note": "Paid nap pods and silence rooms for the overstimulated.",
        "photo_url": "https://images.unsplash.com/photo-1541783245831-57a80c246288?w=800",
        "operating_hours": "10:00 – 20:00",
        "tier": "free",
    },
    {
        "name": "Grain & Grace",
        "category": "coffee",
        "address": "Zheltoksan 115, Almaty",
        "latitude": 43.2534,
        "longitude": 76.9289,
        "vibe_tags": ["#Sourdough", "#Breakfast", "#Artisan"],
        "editorial_note": "House-baked sourdough with single-origin filter coffee.",
        "photo_url": "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800",
        "operating_hours": "8:00 – 16:00",
        "tier": "free",
    },
    {
        "name": "Peak Performance",
        "category": "other",
        "address": "Al-Farabi 15, Almaty",
        "latitude": 43.2189,
        "longitude": 76.9123,
        "vibe_tags": ["#Gym", "#CrossFit", "#Community"],
        "editorial_note": "Functional fitness with a strong community vibe.",
        "photo_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
        "operating_hours": "6:00 – 22:00",
        "tier": "free",
    },
    {
        "name": "Moonlight Yoga",
        "category": "yoga",
        "address": "Kabanbay Batyr 62, Almaty",
        "latitude": 43.2278,
        "longitude": 76.9234,
        "vibe_tags": ["#Moon", "#Evening", "#Restorative"],
        "editorial_note": "Full moon flows and candlelit restorative sessions.",
        "photo_url": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
        "operating_hours": "18:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "Herbal Haven",
        "category": "other",
        "address": "Gogol 88, Almaty",
        "latitude": 43.2612,
        "longitude": 76.9389,
        "vibe_tags": ["#Tea", "#Herbal", "#Wellness"],
        "editorial_note": "Tisane bar with locally foraged herbs and tonics.",
        "photo_url": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800",
        "operating_hours": "10:00 – 20:00",
        "tier": "free",
    },
    {
        "name": "Canvas Coffee",
        "category": "coffee",
        "address": "Baitursynov 120, Almaty",
        "latitude": 43.2334,
        "longitude": 76.8934,
        "vibe_tags": ["#Art", "#Gallery", "#LatteArt"],
        "editorial_note": "Coffee shop meets micro-gallery. Latte art competitions monthly.",
        "photo_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
        "operating_hours": "9:00 – 21:00",
        "tier": "free",
    },
    {
        "name": "Restore Clinic",
        "category": "spa",
        "address": "Satpaev 30, Almaty",
        "latitude": 43.2456,
        "longitude": 76.9067,
        "vibe_tags": ["#Physio", "#Recovery", "#Sports"],
        "editorial_note": "Sports massage and recovery treatments for active urbanites.",
        "photo_url": "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800",
        "operating_hours": "9:00 – 19:00",
        "tier": "free",
    },
    {
        "name": "Morning Light Studio",
        "category": "yoga",
        "address": "Kunaev 15, Almaty",
        "latitude": 43.2512,
        "longitude": 76.9512,
        "vibe_tags": ["#Sunrise", "#Intention", "#Journal"],
        "editorial_note": "Sunrise yoga followed by guided journaling. The Aura origin spot.",
        "photo_url": "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800",
        "operating_hours": "6:00 – 10:00",
        "tier": "featured",
    },
    {
        "name": "Esentai Park Walk",
        "category": "other",
        "address": "Esentai, Almaty",
        "latitude": 43.2089,
        "longitude": 76.9234,
        "vibe_tags": ["#Walk", "#Park", "#Social"],
        "editorial_note": "The city's favorite evening stroll. Light a beacon and meet here.",
        "photo_url": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
        "operating_hours": "Always open",
        "tier": "free",
    },
]
